feat(templates): using template for error page
WPO-Foundation/webpagetest pull request #1617
Opened 2021-11-09 00:02 UTC by jefflembeck

This introduces the concept of a template helper.

This can be used so we better separate our logic from our templates as
we build out pages

2021-11-09 13:46 UTC, tkadlec requested changes

2021-11-09 13:46 UTC, tkadlec commented on www/runtest.php
> -    global $USER_EMAIL;
`$USER_EMAIL`, `$supportsAuth` and `$supportsSaml` all get used by the header, so we need to get this information into the template somehow. (I don't see footer referencing any of these, nor do I see `$privateInstall` used at all here)

These all feel like the kind of global information we may just want to have readily available to templates throughout in some way. Does it make sense for the template class to magically pull in some basic global data or is it better to be explicit about this?

2021-11-09 20:45 UTC, scottjehl commented
👍

2021-11-09 22:00 UTC, tkadlec approved these changes
LGTM!

2021-11-11 15:11 UTC, tkadlec commented
Niiice! I like the changes. Not _crazy_ about the duplicate files, but I know that's temporary and we'll work towards fixing that up.

2021-11-11 15:35 UTC, merged